const vecProto = {x:0,y:0,z:0,w:0,type:4,
                  toString() {
                    function str2(v) {
                      return "["+v.x+","+v.y+"]"
                    }
                    function str3(v) {
                      return "["+v.x+","+v.y+","+v.z+"]"
                    }
                    function str4(v) {
                      return "["+v.x+","+v.y+","+v.z+","+v.w+"]"
                    }
                    return [str2,str3,str4][this.type-2](this)
                  },
                  get xx() {return vec2(this.x,this.x)},
                  get xy() {return vec2(this.x,this.y)},
                  get xz() {return vec2(this.x,this.z??0)},
                  get xw() {return vec2(this.x,this.w??0)},
                  get yx() {return vec2(this.y,this.x)},
                  get yy() {return vec2(this.y,this.y)},
                  get yz() {return vec2(this.y,this.z??0)},
                  get yw() {return vec2(this.y,this.w??0)},
                  get zx() {return vec2(this.z??0,this.x)},
                  get zy() {return vec2(this.z??0,this.y)},
                  get zz() {return vec2(this.z??0,this.z??0)},
                  get zw() {return vec2(this.z??0,this.w??0)},
                  get wx() {return vec2(this.w??0,this.x)},
                  get wy() {return vec2(this.w??0,this.y)},
                  get wz() {return vec2(this.w??0,this.z??0)},
                  get ww() {return vec2(this.w??0,this.w??0)},
                  get xxx() {return vec3(this.x,this.x,this.x)},
                  get xxy() {return vec3(this.x,this.x,this.y)},
                  get xxz() {return vec3(this.x,this.x,this.z??0)},
                  get xxw() {return vec3(this.x,this.x,this.w??0)},
                  get xyx() {return vec3(this.x,this.y,this.x)},
                  get xyy() {return vec3(this.x,this.y,this.y)},
                  get xyz() {return vec3(this.x,this.y,this.z??0)},
                  get xyw() {return vec3(this.x,this.y,this.w??0)},
                  get xzx() {return vec3(this.x,this.z??0,this.x)},
                  get xzy() {return vec3(this.x,this.z??0,this.y)},
                  get xzz() {return vec3(this.x,this.z??0,this.z??0)},
                  get xzw() {return vec3(this.x,this.z??0,this.w??0)},
                  get xwx() {return vec3(this.x,this.w??0,this.x)},
                  get xwy() {return vec3(this.x,this.w??0,this.y)},
                  get xwz() {return vec3(this.x,this.w??0,this.z??0)},
                  get xww() {return vec3(this.x,this.w??0,this.w??0)},
                  get yxx() {return vec3(this.y,this.x,this.x)},
                  get yxy() {return vec3(this.y,this.x,this.y)},
                  get yxz() {return vec3(this.y,this.x,this.z??0)},
                  get yxw() {return vec3(this.y,this.x,this.w??0)},
                  get yyx() {return vec3(this.y,this.y,this.x)},
                  get yyy() {return vec3(this.y,this.y,this.y)},
                  get yyz() {return vec3(this.y,this.y,this.z??0)},
                  get yyw() {return vec3(this.y,this.y,this.w??0)},
                  get yzx() {return vec3(this.y,this.z??0,this.x)},
                  get yzy() {return vec3(this.y,this.z??0,this.y)},
                  get yzz() {return vec3(this.y,this.z??0,this.z??0)},
                  get yzw() {return vec3(this.y,this.z??0,this.w??0)},
                  get ywx() {return vec3(this.y,this.w??0,this.x)},
                  get ywy() {return vec3(this.y,this.w??0,this.y)},
                  get ywz() {return vec3(this.y,this.w??0,this.z??0)},
                  get yww() {return vec3(this.y,this.w??0,this.w??0)},
                  get zxx() {return vec3(this.z??0,this.x,this.x)},
                  get zxy() {return vec3(this.z??0,this.x,this.y)},
                  get zxz() {return vec3(this.z??0,this.x,this.z??0)},
                  get zxw() {return vec3(this.z??0,this.x,this.w??0)},
                  get zyx() {return vec3(this.z??0,this.y,this.x)},
                  get zyy() {return vec3(this.z??0,this.y,this.y)},
                  get zyz() {return vec3(this.z??0,this.y,this.z??0)},
                  get zyw() {return vec3(this.z??0,this.y,this.w??0)},
                  get zzx() {return vec3(this.z??0,this.z??0,this.x)},
                  get zzy() {return vec3(this.z??0,this.z??0,this.y)},
                  get zzz() {return vec3(this.z??0,this.z??0,this.z??0)},
                  get zzw() {return vec3(this.z??0,this.z??0,this.w??0)},
                  get zwx() {return vec3(this.z??0,this.w??0,this.x)},
                  get zwy() {return vec3(this.z??0,this.w??0,this.y)},
                  get zwz() {return vec3(this.z??0,this.w??0,this.z??0)},
                  get zww() {return vec3(this.z??0,this.w??0,this.w??0)},
                  get wxx() {return vec3(this.w??0,this.x,this.x)},
                  get wxy() {return vec3(this.w??0,this.x,this.y)},
                  get wxz() {return vec3(this.w??0,this.x,this.z??0)},
                  get wxw() {return vec3(this.w??0,this.x,this.w??0)},
                  get wyx() {return vec3(this.w??0,this.y,this.x)},
                  get wyy() {return vec3(this.w??0,this.y,this.y)},
                  get wyz() {return vec3(this.w??0,this.y,this.z??0)},
                  get wyw() {return vec3(this.w??0,this.y,this.w??0)},
                  get wzx() {return vec3(this.w??0,this.z??0,this.x)},
                  get wzy() {return vec3(this.w??0,this.z??0,this.y)},
                  get wzz() {return vec3(this.w??0,this.z??0,this.z??0)},
                  get wzw() {return vec3(this.w??0,this.z??0,this.w??0)},
                  get wwx() {return vec3(this.w??0,this.w??0,this.x)},
                  get wwy() {return vec3(this.w??0,this.w??0,this.y)},
                  get wwz() {return vec3(this.w??0,this.w??0,this.z??0)},
                  get www() {return vec3(this.w??0,this.w??0,this.w??0)},
                  get xxxx() {return vec4(this.x,this.x,this.x,this.x)},
                  get xxxy() {return vec4(this.x,this.x,this.x,this.y)},
                  get xxxz() {return vec4(this.x,this.x,this.x,this.z??0)},
                  get xxxw() {return vec4(this.x,this.x,this.x,this.w??0)},
                  get xxyx() {return vec4(this.x,this.x,this.y,this.x)},
                  get xxyy() {return vec4(this.x,this.x,this.y,this.y)},
                  get xxyz() {return vec4(this.x,this.x,this.y,this.z??0)},
                  get xxyw() {return vec4(this.x,this.x,this.y,this.w??0)},
                  get xxzx() {return vec4(this.x,this.x,this.z??0,this.x)},
                  get xxzy() {return vec4(this.x,this.x,this.z??0,this.y)},
                  get xxzz() {return vec4(this.x,this.x,this.z??0,this.z)},
                  get xxzw() {return vec4(this.x,this.x,this.z??0,this.w)},
                  get xxwx() {return vec4(this.x,this.x,this.w??0,this.x)},
                  get xxwy() {return vec4(this.x,this.x,this.w??0,this.y)},
                  get xxwz() {return vec4(this.x,this.x,this.w??0,this.z)},
                  get xxww() {return vec4(this.x,this.x,this.w??0,this.w)},
                  get xyxx() {return vec4(this.x,this.y,this.x,this.x)},
                  get xyxy() {return vec4(this.x,this.y,this.x,this.y)},
                  get xyxz() {return vec4(this.x,this.y,this.x,this.z??0)},
                  get xyxw() {return vec4(this.x,this.y,this.x,this.w??0)},
                  get xyyx() {return vec4(this.x,this.y,this.y,this.x)},
                  get xyyy() {return vec4(this.x,this.y,this.y,this.y)},
                  get xyyz() {return vec4(this.x,this.y,this.y,this.z??0)},
                  get xyyw() {return vec4(this.x,this.y,this.y,this.w??0)},
                  get xyzx() {return vec4(this.x,this.y,this.z,this.x)},
                  get xyzy() {return vec4(this.x,this.y,this.z,this.y)},
                  get xyzz() {return vec4(this.x,this.y,this.z,this.z??0)},
                  get xyzw() {return vec4(this.x,this.y,this.z,this.w??0)},
                  get xywx() {return vec4(this.x,this.y,this.w,this.x)},
                  get xywy() {return vec4(this.x,this.y,this.w,this.y)},
                  get xywz() {return vec4(this.x,this.y,this.w,this.z??0)},
                  get xyww() {return vec4(this.x,this.y,this.w,this.w??0)},
                  get xzxx() {return vec4(this.x,this.z??0,this.x,this.x)},
                  get xzxy() {return vec4(this.x,this.z??0,this.x,this.y)},
                  get xzxz() {return vec4(this.x,this.z??0,this.x,this.z??0)},
                  get xzxw() {return vec4(this.x,this.z??0,this.x,this.w??0)},
                  get xzyx() {return vec4(this.x,this.z??0,this.y,this.x)},
                  get xzyy() {return vec4(this.x,this.z??0,this.y,this.y)},
                  get xzyz() {return vec4(this.x,this.z??0,this.y,this.z??0)},
                  get xzyw() {return vec4(this.x,this.z??0,this.y,this.w??0)},
                  get xzzx() {return vec4(this.x,this.z??0,this.z,this.x)},
                  get xzzy() {return vec4(this.x,this.z??0,this.z,this.y)},
                  get xzzz() {return vec4(this.x,this.z??0,this.z,this.z??0)},
                  get xzzw() {return vec4(this.x,this.z??0,this.z,this.w??0)},
                  get xzwx() {return vec4(this.x,this.z??0,this.w,this.x)},
                  get xzwy() {return vec4(this.x,this.z??0,this.w,this.y)},
                  get xzwz() {return vec4(this.x,this.z??0,this.w,this.z??0)},
                  get xzww() {return vec4(this.x,this.z??0,this.w,this.w??0)},
                  get xwxx() {return vec4(this.x,this.w??0,this.x,this.x)},
                  get xwxy() {return vec4(this.x,this.w??0,this.x,this.y)},
                  get xwxz() {return vec4(this.x,this.w??0,this.x,this.z??0)},
                  get xwxw() {return vec4(this.x,this.w??0,this.x,this.w??0)},
                  get xwyx() {return vec4(this.x,this.w??0,this.y,this.x)},
                  get xwyy() {return vec4(this.x,this.w??0,this.y,this.y)},
                  get xwyz() {return vec4(this.x,this.w??0,this.y,this.z??0)},
                  get xwyw() {return vec4(this.x,this.w??0,this.y,this.w??0)},
                  get xwzx() {return vec4(this.x,this.w??0,this.z,this.x)},
                  get xwzy() {return vec4(this.x,this.w??0,this.z,this.y)},
                  get xwzz() {return vec4(this.x,this.w??0,this.z,this.z??0)},
                  get xwzw() {return vec4(this.x,this.w??0,this.z,this.w??0)},
                  get xwwx() {return vec4(this.x,this.w??0,this.w,this.x)},
                  get xwwy() {return vec4(this.x,this.w??0,this.w,this.y)},
                  get xwwz() {return vec4(this.x,this.w??0,this.w,this.z??0)},
                  get xwww() {return vec4(this.x,this.w??0,this.w,this.w??0)},
                  get yxxx() {return vec4(this.y,this.x,this.x,this.x)},
                  get yxxy() {return vec4(this.y,this.x,this.x,this.y)},
                  get yxxz() {return vec4(this.y,this.x,this.x,this.z??0)},
                  get yxxw() {return vec4(this.y,this.x,this.x,this.w??0)},
                  get yxyx() {return vec4(this.y,this.x,this.y,this.x)},
                  get yxyy() {return vec4(this.y,this.x,this.y,this.y)},
                  get yxyz() {return vec4(this.y,this.x,this.y,this.z??0)},
                  get yxyw() {return vec4(this.y,this.x,this.y,this.w??0)},
                  get yxzx() {return vec4(this.y,this.x,this.z??0,this.x)},
                  get yxzy() {return vec4(this.y,this.x,this.z??0,this.y)},
                  get yxzz() {return vec4(this.y,this.x,this.z??0,this.z??0)},
                  get yxzw() {return vec4(this.y,this.x,this.z??0,this.w??0)},
                  get yxwx() {return vec4(this.y,this.x,this.w??0,this.x)},
                  get yxwy() {return vec4(this.y,this.x,this.w??0,this.y)},
                  get yxwz() {return vec4(this.y,this.x,this.w??0,this.z??0)},
                  get yxww() {return vec4(this.y,this.x,this.w??0,this.w??0)},
                  get yyxx() {return vec4(this.y,this.y,this.x,this.x)},
                  get yyxy() {return vec4(this.y,this.y,this.x,this.y)},
                  get yyxz() {return vec4(this.y,this.y,this.x,this.z??0)},
                  get yyxw() {return vec4(this.y,this.y,this.x,this.w??0)},
                  get yyyx() {return vec4(this.y,this.y,this.y,this.x)},
                  get yyyy() {return vec4(this.y,this.y,this.y,this.y)},
                  get yyyz() {return vec4(this.y,this.y,this.y,this.z??0)},
                  get yyyw() {return vec4(this.y,this.y,this.y,this.w??0)},
                  get yyzx() {return vec4(this.y,this.y,this.z??0,this.x)},
                  get yyzy() {return vec4(this.y,this.y,this.z??0,this.y)},
                  get yyzz() {return vec4(this.y,this.y,this.z??0,this.z??0)},
                  get yyzw() {return vec4(this.y,this.y,this.z??0,this.w??0)},
                  get yywx() {return vec4(this.y,this.y,this.w??0,this.x)},
                  get yywy() {return vec4(this.y,this.y,this.w??0,this.y)},
                  get yywz() {return vec4(this.y,this.y,this.w??0,this.z??0)},
                  get yyww() {return vec4(this.y,this.y,this.w??0,this.w??0)},
                  get yzxx() {return vec4(this.y,this.z??0,this.x,this.x)},
                  get yzxy() {return vec4(this.y,this.z??0,this.x,this.y)},
                  get yzxz() {return vec4(this.y,this.z??0,this.x,this.z??0)},
                  get yzxw() {return vec4(this.y,this.z??0,this.x,this.w??0)},
                  get yzyx() {return vec4(this.y,this.z??0,this.y,this.x)},
                  get yzyy() {return vec4(this.y,this.z??0,this.y,this.y)},
                  get yzyz() {return vec4(this.y,this.z??0,this.y,this.z??0)},
                  get yzyw() {return vec4(this.y,this.z??0,this.y,this.w??0)},
                  get yzzx() {return vec4(this.y,this.z??0,this.z??0,this.x)},
                  get yzzy() {return vec4(this.y,this.z??0,this.z??0,this.y)},
                  get yzzz() {return vec4(this.y,this.z??0,this.z??0,this.z??0)},
                  get yzzw() {return vec4(this.y,this.z??0,this.z??0,this.w??0)},
                  get yzwx() {return vec4(this.y,this.z??0,this.w??0,this.x)},
                  get yzwy() {return vec4(this.y,this.z??0,this.w??0,this.y)},
                  get yzwz() {return vec4(this.y,this.z??0,this.w??0,this.z??0)},
                  get yzww() {return vec4(this.y,this.z??0,this.w??0,this.w??0)},
                  get ywxx() {return vec4(this.y,this.w??0,this.x,this.x)},
                  get ywxy() {return vec4(this.y,this.w??0,this.x,this.y)},
                  get ywxz() {return vec4(this.y,this.w??0,this.x,this.z??0)},
                  get ywxw() {return vec4(this.y,this.w??0,this.x,this.w??0)},
                  get ywyx() {return vec4(this.y,this.w??0,this.y,this.x)},
                  get ywyy() {return vec4(this.y,this.w??0,this.y,this.y)},
                  get ywyz() {return vec4(this.y,this.w??0,this.y,this.z??0)},
                  get ywyw() {return vec4(this.y,this.w??0,this.y,this.w??0)},
                  get ywzx() {return vec4(this.y,this.w??0,this.z??0,this.x)},
                  get ywzy() {return vec4(this.y,this.w??0,this.z??0,this.y)},
                  get ywzz() {return vec4(this.y,this.w??0,this.z??0,this.z??0)},
                  get ywzw() {return vec4(this.y,this.w??0,this.z??0,this.w??0)},
                  get ywwx() {return vec4(this.y,this.w??0,this.w??0,this.x)},
                  get ywwy() {return vec4(this.y,this.w??0,this.w??0,this.y)},
                  get ywwz() {return vec4(this.y,this.w??0,this.w??0,this.z??0)},
                  get ywww() {return vec4(this.y,this.w??0,this.w??0,this.w??0)},
                  get zxxx() {return vec4(this.z??0,this.x,this.x,this.x)},
                  get zxxy() {return vec4(this.z??0,this.x,this.x,this.y)},
                  get zxxz() {return vec4(this.z??0,this.x,this.x,this.z??0)},
                  get zxxw() {return vec4(this.z??0,this.x,this.x,this.w??0)},
                  get zxyx() {return vec4(this.z??0,this.x,this.y,this.x)},
                  get zxyy() {return vec4(this.z??0,this.x,this.y,this.y)},
                  get zxyz() {return vec4(this.z??0,this.x,this.y,this.z??0)},
                  get zxyw() {return vec4(this.z??0,this.x,this.y,this.w??0)},
                  get zxzx() {return vec4(this.z??0,this.x,this.z??0,this.x)},
                  get zxzy() {return vec4(this.z??0,this.x,this.z??0,this.y)},
                  get zxzz() {return vec4(this.z??0,this.x,this.z??0,this.z??0)},
                  get zxzw() {return vec4(this.z??0,this.x,this.z??0,this.w??0)},
                  get zxwx() {return vec4(this.z??0,this.x,this.w??0,this.x)},
                  get zxwy() {return vec4(this.z??0,this.x,this.w??0,this.y)},
                  get zxwz() {return vec4(this.z??0,this.x,this.w??0,this.z??0)},
                  get zxww() {return vec4(this.z??0,this.x,this.w??0,this.w??0)},
                  get zyxx() {return vec4(this.z??0,this.y,this.x,this.x)},
                  get zyxy() {return vec4(this.z??0,this.y,this.x,this.y)},
                  get zyxz() {return vec4(this.z??0,this.y,this.x,this.z??0)},
                  get zyxw() {return vec4(this.z??0,this.y,this.x,this.w??0)},
                  get zyyx() {return vec4(this.z??0,this.y,this.y,this.x)},
                  get zyyy() {return vec4(this.z??0,this.y,this.y,this.y)},
                  get zyyz() {return vec4(this.z??0,this.y,this.y,this.z??0)},
                  get zyyw() {return vec4(this.z??0,this.y,this.y,this.w??0)},
                  get zyzx() {return vec4(this.z??0,this.y,this.z??0,this.x)},
                  get zyzy() {return vec4(this.z??0,this.y,this.z??0,this.y)},
                  get zyzz() {return vec4(this.z??0,this.y,this.z??0,this.z??0)},
                  get zyzw() {return vec4(this.z??0,this.y,this.z??0,this.w??0)},
                  get zywx() {return vec4(this.z??0,this.y,this.w??0,this.x)},
                  get zywy() {return vec4(this.z??0,this.y,this.w??0,this.y)},
                  get zywz() {return vec4(this.z??0,this.y,this.w??0,this.z??0)},
                  get zyww() {return vec4(this.z??0,this.y,this.w??0,this.w??0)},
                  get zzxx() {return vec4(this.z??0,this.z??0,this.x,this.x)},
                  get zzxy() {return vec4(this.z??0,this.z??0,this.x,this.y)},
                  get zzxz() {return vec4(this.z??0,this.z??0,this.x,this.z??0)},
                  get zzxw() {return vec4(this.z??0,this.z??0,this.x,this.w??0)},
                  get zzyx() {return vec4(this.z??0,this.z??0,this.y,this.x)},
                  get zzyy() {return vec4(this.z??0,this.z??0,this.y,this.y)},
                  get zzyz() {return vec4(this.z??0,this.z??0,this.y,this.z??0)},
                  get zzyw() {return vec4(this.z??0,this.z??0,this.y,this.w??0)},
                  get zzzx() {return vec4(this.z??0,this.z??0,this.z??0,this.x)},
                  get zzzy() {return vec4(this.z??0,this.z??0,this.z??0,this.y)},
                  get zzzz() {return vec4(this.z??0,this.z??0,this.z??0,this.z??0)},
                  get zzzw() {return vec4(this.z??0,this.z??0,this.z??0,this.w??0)},
                  get zzwx() {return vec4(this.z??0,this.z??0,this.w??0,this.x)},
                  get zzwy() {return vec4(this.z??0,this.z??0,this.w??0,this.y)},
                  get zzwz() {return vec4(this.z??0,this.z??0,this.w??0,this.z??0)},
                  get zzww() {return vec4(this.z??0,this.z??0,this.w??0,this.w??0)},
                  get zwxx() {return vec4(this.z??0,this.w??0,this.x,this.x)},
                  get zwxy() {return vec4(this.z??0,this.w??0,this.x,this.y)},
                  get zwxz() {return vec4(this.z??0,this.w??0,this.x,this.z??0)},
                  get zwxw() {return vec4(this.z??0,this.w??0,this.x,this.w??0)},
                  get zwyx() {return vec4(this.z??0,this.w??0,this.y,this.x)},
                  get zwyy() {return vec4(this.z??0,this.w??0,this.y,this.y)},
                  get zwyz() {return vec4(this.z??0,this.w??0,this.y,this.z??0)},
                  get zwyw() {return vec4(this.z??0,this.w??0,this.y,this.w??0)},
                  get zwzx() {return vec4(this.z??0,this.w??0,this.z??0,this.x)},
                  get zwzy() {return vec4(this.z??0,this.w??0,this.z??0,this.y)},
                  get zwzz() {return vec4(this.z??0,this.w??0,this.z??0,this.z??0)},
                  get zwzw() {return vec4(this.z??0,this.w??0,this.z??0,this.w??0)},
                  get zwwx() {return vec4(this.z??0,this.w??0,this.w??0,this.x)},
                  get zwwy() {return vec4(this.z??0,this.w??0,this.w??0,this.y)},
                  get zwwz() {return vec4(this.z??0,this.w??0,this.w??0,this.z??0)},
                  get zwww() {return vec4(this.z??0,this.w??0,this.w??0,this.w??0)},
                  get wxxx() {return vec4(this.w??0,this.x,this.x,this.x)},
                  get wxxy() {return vec4(this.w??0,this.x,this.x,this.y)},
                  get wxxz() {return vec4(this.w??0,this.x,this.x,this.z??0)},
                  get wxxw() {return vec4(this.w??0,this.x,this.x,this.w??0)},
                  get wxyx() {return vec4(this.w??0,this.x,this.y,this.x)},
                  get wxyy() {return vec4(this.w??0,this.x,this.y,this.y)},
                  get wxyz() {return vec4(this.w??0,this.x,this.y,this.z??0)},
                  get wxyw() {return vec4(this.w??0,this.x,this.y,this.w??0)},
                  get wxzx() {return vec4(this.w??0,this.x,this.z??0,this.x)},
                  get wxzy() {return vec4(this.w??0,this.x,this.z??0,this.y)},
                  get wxzz() {return vec4(this.w??0,this.x,this.z??0,this.z??0)},
                  get wxzw() {return vec4(this.w??0,this.x,this.z??0,this.w??0)},
                  get wxwx() {return vec4(this.w??0,this.x,this.w??0,this.x)},
                  get wxwy() {return vec4(this.w??0,this.x,this.w??0,this.y)},
                  get wxwz() {return vec4(this.w??0,this.x,this.w??0,this.z??0)},
                  get wxww() {return vec4(this.w??0,this.x,this.w??0,this.w??0)},
                  get wyxx() {return vec4(this.w??0,this.y,this.x,this.x)},
                  get wyxy() {return vec4(this.w??0,this.y,this.x,this.y)},
                  get wyxz() {return vec4(this.w??0,this.y,this.x,this.z??0)},
                  get wyxw() {return vec4(this.w??0,this.y,this.x,this.w??0)},
                  get wyyx() {return vec4(this.w??0,this.y,this.y,this.x)},
                  get wyyy() {return vec4(this.w??0,this.y,this.y,this.y)},
                  get wyyz() {return vec4(this.w??0,this.y,this.y,this.z??0)},
                  get wyyw() {return vec4(this.w??0,this.y,this.y,this.w??0)},
                  get wyzx() {return vec4(this.w??0,this.y,this.z??0,this.x)},
                  get wyzy() {return vec4(this.w??0,this.y,this.z??0,this.y)},
                  get wyzz() {return vec4(this.w??0,this.y,this.z??0,this.z??0)},
                  get wyzw() {return vec4(this.w??0,this.y,this.z??0,this.w??0)},
                  get wywx() {return vec4(this.w??0,this.y,this.w??0,this.x)},
                  get wywy() {return vec4(this.w??0,this.y,this.w??0,this.y)},
                  get wywz() {return vec4(this.w??0,this.y,this.w??0,this.z??0)},
                  get wyww() {return vec4(this.w??0,this.y,this.w??0,this.w??0)},
                  get wzxx() {return vec4(this.w??0,this.z??0,this.x,this.x)},
                  get wzxy() {return vec4(this.w??0,this.z??0,this.x,this.y)},
                  get wzxz() {return vec4(this.w??0,this.z??0,this.x,this.z??0)},
                  get wzxw() {return vec4(this.w??0,this.z??0,this.x,this.w??0)},
                  get wzyx() {return vec4(this.w??0,this.z??0,this.y,this.x)},
                  get wzyy() {return vec4(this.w??0,this.z??0,this.y,this.y)},
                  get wzyz() {return vec4(this.w??0,this.z??0,this.y,this.z??0)},
                  get wzyw() {return vec4(this.w??0,this.z??0,this.y,this.w??0)},
                  get wzzx() {return vec4(this.w??0,this.z??0,this.z??0,this.x)},
                  get wzzy() {return vec4(this.w??0,this.z??0,this.z??0,this.y)},
                  get wzzz() {return vec4(this.w??0,this.z??0,this.z??0,this.z??0)},
                  get wzzw() {return vec4(this.w??0,this.z??0,this.z??0,this.w??0)},
                  get wzwx() {return vec4(this.w??0,this.z??0,this.w??0,this.x)},
                  get wzwy() {return vec4(this.w??0,this.z??0,this.w??0,this.y)},
                  get wzwz() {return vec4(this.w??0,this.z??0,this.w??0,this.z??0)},
                  get wzww() {return vec4(this.w??0,this.z??0,this.w??0,this.w??0)},
                  get wwxx() {return vec4(this.w??0,this.w??0,this.x,this.x)},
                  get wwxy() {return vec4(this.w??0,this.w??0,this.x,this.y)},
                  get wwxz() {return vec4(this.w??0,this.w??0,this.x,this.z??0)},
                  get wwxw() {return vec4(this.w??0,this.w??0,this.x,this.w??0)},
                  get wwyx() {return vec4(this.w??0,this.w??0,this.y,this.x)},
                  get wwyy() {return vec4(this.w??0,this.w??0,this.y,this.y)},
                  get wwyz() {return vec4(this.w??0,this.w??0,this.y,this.z??0)},
                  get wwyw() {return vec4(this.w??0,this.w??0,this.y,this.w??0)},
                  get wwzx() {return vec4(this.w??0,this.w??0,this.z??0,this.x)},
                  get wwzy() {return vec4(this.w??0,this.w??0,this.z??0,this.y)},
                  get wwzz() {return vec4(this.w??0,this.w??0,this.z??0,this.z??0)},
                  get wwzw() {return vec4(this.w??0,this.w??0,this.z??0,this.w??0)},
                  get wwwx() {return vec4(this.w??0,this.w??0,this.w??0,this.x)},
                  get wwwy() {return vec4(this.w??0,this.w??0,this.w??0,this.y)},
                  get wwwz() {return vec4(this.w??0,this.w??0,this.w??0,this.z??0)},
                  get wwww() {return vec4(this.w??0,this.w??0,this.w??0,this.w??0)},
                  }
function vector(x,y,z,w,type) {
  return Object.defineProperties(Object.create(vecProto),{x:{value:x,writable:(x!=null)},y:{value:y,writable:(y!=null)},z:{value:z,writable:(z!=null)},w:{value:w,writable:(w!=null)},type:{value:type,writable:false}})
}
function vec2(x=0,y=x) {
  console.log()
  if (x.prototype===vecProto) {
    return vector(x.x,x.y,null,null,2)
  }
  return vector(x,y,null,null,2)
}
function vec3(x=0,y=x,z=y) {
  if (x.prototype===vecProto) {
    return vector(x.x,x.y,x.z,null,3)
  }
  return vector(x,y,z,null,3)
}
function vec4(x=0,y=x,z=y,w=z) {
  if (x.prototype===vecProto) {
    return vector(x.x,x.y,x.z,x.w,4)
  }
  return vector(x,y,z,w,4)
}
function length(v) {
  if (typeof v=="number") return v
  
  return Math.hypot(v.x,v.y,v.z,v.w)
}
function normalize(v) {
  if (typeof v=="number") return 1
  const len = 1/Math.hypot(v.x,v.y,v.z,v.w)
  return [vec2,vec3,vec4][v.type-2](v.x*len,v.y*len,v.z*len,v.w*len)
}
function add(a,b) {
  return (typeof a=="number"&&typeof b=="number")?
    a+b:
  [vec2,vec3,vec4][(a.type>b.type?a.type:b.type)-2](a.x+b.x,
                                                    a.y+b.y,
                                                    a.z+b.z,
                                                    a.w+b.w)
}
function sub(a,b) {
  return (typeof a=="number"&&typeof b=="number")?
    a-b:
  [vec2,vec3,vec4][(a.type>b.type?a.type:b.type)-2](a.x-b.x,
                                                    a.y-b.y,
                                                    a.z-b.z,
                                                    a.w-b.w)
}
function mul(a,b) {
  const max = (a.type>b.type?a.type:b.type)-2
  const av = (typeof a=="number")?[vec2,vec3,vec4][max](a):a
  const bv = (typeof b=="number")?[vec2,vec3,vec4][max](b):b
  return (typeof a=="number"&&typeof b=="number")?
    a*b:
  [vec2,vec3,vec4][max](av.x*bv.x,
                        av.y*bv.y,
                        (av.z??1)*(bv.z??1),
                        (av.w??1)*(bv.w??1))
}
function div(a,b) {
  const max = (a.type>b.type?a.type:b.type)-2
  const ta=typeof a
  const tb=typeof b
  if (ta=="number"&&tb=="number") {
    return a/b
  }
  const av = (typeof a=="number")?[vec2,vec3,vec4][max](a):a
  const bv = (typeof b=="number")?[vec2,vec3,vec4][max](b):b
  return [vec2,vec3,vec4][max](av.x/bv.x,
                              av.y/bv.y,
                              (av.z??(bv.z*bv.z))/(bv.z??1),
                              (av.w??(bv.z*bv.z))/(bv.w??1))
}
a=vec2(2,6)
console.log(div(3,2))
console.log(div(a,vec3(4,8,5)))
console.log(a)
a.toString()